pipeline{
    agent any
    stages{
        stage('checkout'){
            steps{
                git 'https://github.com/your-repo/ReactTodoApp.git'
            }    
        }

        stage('build'){
            steps{
                sh 'docker built -t react-todo-app .'
            }
        }

        stage('Push to Docker Hub'){
            steps{
                withCredentials([url: 'https://index.docker.io/v1/', credentialsId: 'docker-hub-credentials']) {
                    sh 'docker tag react-todo-app your-docker-hub-username/react-todo-app'
                    sh 'docker push your-docker-hub-username/react-todo-app'

                }
            }
        }

        stage('Deploy to CD Server'){
            steps{
                ansiblePlaybook playbook: 'Ansible/playbook.yml', inventory: 'Ansible/inventory'
            }
        }
    }
}    
    

