---
- name: Install Jenkins on ubuntu 
  hosts: Jenkins
  become: yes
  tasks:

    - name: Install Java (Required for jenkins)
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
    
    - name: Add Jenkins repository key
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: update apt cache
      apt:
        update_cache: yes 

    - name: Install Jenkins 
      apt:
        name: jenkins
        state: present

    - name: Start jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: ENsure Jenkins is accessible on port 8080
      ufw:
        rule: allow
        port: 8080
        proto: tcp  

    
